name: cashu_app
description: >-
  A reference app for Cashu.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cdk_flutter:
    git:
      url: https://github.com/davidcaseria/cdk_flutter.git
      ref: master
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail_image_network: ^1.2.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
